---
name: Enable Automerge of a pull request from Renovate

on:
  workflow_call:
    inputs:
      renovate_login:
        required: false
        type: string
        default: renovate[bot]
    secrets:
      github_token:
        required: false
      github_app_id:
        required: false
      github_app_private_key:
        required: false

jobs:
  enable_automerge:
    # Enable automerge to merge pull requests from Renovate automatically.
    runs-on: ubuntu-latest
    permissions: {}
    # "! failure() && ! cancelled()" is required. success() returns false if dependent jobs are skipped. https://github.com/community/community/discussions/45058
    # By default success() is used so we have to override success() by "! failure() && ! cancelled()"
    if: |
      ! failure() && ! cancelled() && github.event.pull_request.user.login == inputs.renovate_login && contains(github.event.pull_request.body, ' **Automerge**: Enabled.')
    steps:
      - uses: suzuki-shunsuke/github-token-action@a058de0a42e494414cf4c112436d663a06fd16c0 # v0.1.0
        id: token
        with:
          github_token: ${{secrets.github_token}}
          github_app_id: ${{secrets.github_app_id}}
          github_app_private_key: ${{secrets.github_app_private_key}}
      - run: gh -R "$GITHUB_REPOSITORY" pr merge --merge --auto --delete-branch "$PR_NUMBER"
        env:
          GITHUB_TOKEN: ${{steps.token.outputs.token}} # Use GitHub App to trigger GitHub Actions Workflow by merge commit.
          PR_NUMBER: ${{github.event.pull_request.number}}
